Employees/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('accounts.urls')),
    path('visits/', include('visits.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('addnew', views.add_new, name='addnew'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.destroy, name='delete'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
]

blog/models.py
from django.db import models
from django.urls import reverse


class Employee(models.Model):
    name = models.CharField(max_length=55)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    image = models.ImageField(upload_to='image/', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'id': self.id})

    def __str__(self):
        return self.name

templates/base.html
{% load static %}
<!doctype html>
<html lang=ru>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%}{%endblock%}</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<header>
    <nav>
        <ul>
            <li><a href="/" class="home">Home</a></li>
            {% if user.is_authenticated %}
                <li class="right-links">Hello, {{ user.username }}!
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li><a href="{% url 'login' %}" class="right-links">Login</a></li>
                <li><a href="{% url 'register' %}" class="right-links">Register</a></li>
            {% endif %}

             <li><a href="{% url 'index_visit' %}" class="home">Visits</a></li>
        </ul>
    </nav>
</header>

<div class="container">
    {%block content%}
    {%endblock%}
</div>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 3
       }
    );
} );


</script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}


{%block content%}

<h1>О сотруднике</h1>
<div class="container_info">

    <div class="employee-info">
        {% if employee.image %}
        <img src="{{ employee.image.url }}">
        {% else %}
        <img src="#">
        {% endif %}
        <div>
            <p><strong>Имя:</strong> {{ employee.name }}</p>
            <p><strong>Email:</strong> {{ employee.email }}</p>
            <p><strong>Телефон:</strong> {{ employee.phone }}</p>

            <a href="{% url 'edit'  employee.id  %}"
               class="btn btn-primary btn-xs"
               data-title="Edit" data-toggle="modal"
               data-target="#edit">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a href="{% url 'delete'  employee.id  %}"
               class="btn btn-danger btn-xs"
               data-title="Delete"
               data-toggle="modal"
               data-target="#delete">
                <span class="glyphicon glyphicon-trash"></span>
            </a>

        </div>
    </div>
</div>
{%endblock%}

templates/edit.html
{% extends "base.html" %}
{%block title%}Add New Employee{%endblock title%}
{%block content%}
<div class="col-md-12">
    <h4>Django Crud</h4>
    <form method="POST" class="post-form" enctype="multipart/form-data" action="/update/{{employee.id}}">
        {% csrf_token%}
        <div class="container">
            <br>
            <div class="forum-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label">Employee ID: </label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
                           value="{{employee.id}}"/>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label">Employee Name: </label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="name" id="id_name" required maxlength="100"
                           value="{{employee.name}}"/>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label">Employee Email: </label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="email" id="id_email" required maxlength="250"
                           value="{{employee.email}}"/>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label">Employee Phone: </label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="phone" id="id_phone" required maxlength="20"
                           value="{{employee.phone}}"/>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label">Employee Image: </label>
                <div class="col-sm-4">
                    {% if employee.image %}
                        <span>
                            Текущий момент стоит:
                            <a class="a-link" href="{{ employee.image.url }}">
                                {{ employee.image }}
                            </a>
                        </span>
                    {% endif %}
                    <input type="file" class="form-control" name="image" id="image"
                           value="{{ employee.image }}"/>
                </div>
            </div>
            <div class="forum-group row">
                <label class="col-sm-2 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success btn-lg">Update</button>
                </div>
            </div>
        </div>
    </form>
</div>
{%endblock content%}

templates/index.html
{% extends "base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
<div class="col-md-12">
    <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4>

    <form method="POST" class="post-form" enctype="multipart/form-data" action="{% url 'addnew' %}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Details</h3>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name:</label>
                <div class="col-sm-4">
                    {{ form.name }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    {{ form.email }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    {{ form.phone }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Image:</label>
                <div class="col-sm-4">
                    {{ form.image }}
                </div>
            </div>
            <div class="form-group row" style="display:flex; gap:30px;">
                <label class="col-sm-1 col-form-label" ></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

templates/show.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add New Employee Records{%endblock title%}
{% block content %}

<div class="col-md-12">

    <span>
        <a href="{% url 'addnew' %}" class="btn btn-primary">Add new Record</a>
    </span>
    <div class="table-responsive">
        <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Image</th>
            <th>Edit</th>
            <th>Delete</th>
            </thead>
            <tbody>
            {%for employee in employees%}
            <tr>
                <td><a class="a-link" href="{{ employee.get_absolute_url }}">{{ employee.id}}</a> </td>
                <td><a class="a-link" href="{{ employee.get_absolute_url }}">{{ employee.name}}</a> </td>
                <td>{{ employee.email}}</td>
                <td>{{ employee.phone}}</td>
                {% if employee.image %}
                    <td><img src="{{ employee.image.url }}" alt="#" width="150" height="150"></td>
                {% else %}
                    <td><img src="{% static 'img/404.png' %}" alt="#" width="150" height="100"></td>
                {% endif %}
                <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ employee.id }}"
                                                                                  class="btn btn-primary btn-xs"
                                                                                  data-title="Edit" data-toggle="modal"
                                                                                  data-target="#edit"><span
                        class="glyphicon glyphicon-pencil"></span></a></p></td>
                <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ employee.id }}"
                                                                                    class="btn btn-danger btn-xs"
                                                                                    data-title="Delete"
                                                                                    data-toggle="modal"
                                                                                    data-target="#delete"><span
                        class="glyphicon glyphicon-trash"></span></a></p></td>
            </tr>
            {%endfor%}

            </tbody>
        </table>
    </div>
</div>
{%endblock content%}